package cm.gov.minfof.model.entity.server.serviceinterface;

import cm.gov.minfof.model.entity.AppModuleImpl;
import cm.gov.minfof.model.entity.common.FamillePfnlViewSDO;
import cm.gov.minfof.model.entity.common.PartiesProduitsPfnlViewSDO;
import cm.gov.minfof.model.entity.common.PartiesRecolteesViewSDO;
import cm.gov.minfof.model.entity.common.ProduitsPfnlViewSDO;
import cm.gov.minfof.model.entity.common.serviceinterface.pfnl_wbs;
import cm.gov.minfof.model.entityviewobject.common.CategorieproduitViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CategorieunitemesureViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CertificatorigineViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CollectepfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.CommuneViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DepartementViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DetailpermisViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DetailscollectepfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.DetailsexportpfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.ExportpfnlViewSDO;
import cm.gov.minfof.model.entityviewobject.common.LettrevoitureViewSDO;
import cm.gov.minfof.model.entityviewobject.common.LocaliteViewSDO;
import cm.gov.minfof.model.entityviewobject.common.OriginespnflsViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PartiproduitSDO;
import cm.gov.minfof.model.entityviewobject.common.PaysViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PermisViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PermissionnairespnflViewSDO;
import cm.gov.minfof.model.entityviewobject.common.PostecontroleViewSDO;
import cm.gov.minfof.model.entityviewobject.common.RegionViewSDO;
import cm.gov.minfof.model.entityviewobject.common.UnitemesureViewSDO;
import cm.gov.minfof.model.queryviewobject.common.RegionsViewSDO;

import java.lang.reflect.Method;

import java.math.BigDecimal;

import java.util.List;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 15 16:36:49 CET 2016
// ---------------------------------------------------------------------
@Stateless(name = "cm.gov.minfof.model.entity.common.pfnl_wbsBean", mappedName = "pfnl_wbsBean")
@Remote(pfnl_wbs.class)
@PortableWebService(targetNamespace = "/cm/gov/minfof/model/entity/common/", serviceName = "pfnl_wbs",
                    portName = "pfnl_wbsSoapHttpPort",
                    endpointInterface = "cm.gov.minfof.model.entity.common.serviceinterface.pfnl_wbs")
@Interceptors({ ServiceContextInterceptor.class })
public class pfnl_wbsImpl extends ServiceImpl implements pfnl_wbs {
    private static boolean _isInited = false;

    /**
     * This is the default constructor (do not remove).
     */
    public pfnl_wbsImpl() {
        init();
        setApplicationModuleDefName("cm.gov.minfof.model.entity.AppModule");
        setConfigurationName("pfnl_wbs");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (pfnl_wbsImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("cm/gov/minfof/model/entity/common/serviceinterface/", "pfnl_wbs.xsd");
                _isInited = true;
            } catch (Throwable t) {
                ADFLogger.createADFLogger(Diagnostic.SERVINT_RT_LOGGER).severe(t);
            }
        }
    }

    /**
     * getCategorieproduitView1: generated method. Do not modify.
     */
    public CategorieproduitViewSDO getCategorieproduitView1(BigDecimal idcategorieproduit) throws ServiceException {
        return (CategorieproduitViewSDO) get(new Object[] { idcategorieproduit }, "CategorieproduitView1",
                                             CategorieproduitViewSDO.class);
    }

    /**
     * findCategorieproduitView1: generated method. Do not modify.
     */
    public List<CategorieproduitViewSDO> findCategorieproduitView1(FindCriteria findCriteria,
                                                                   FindControl findControl) throws ServiceException {
        return (List<CategorieproduitViewSDO>) find(findCriteria, findControl, "CategorieproduitView1",
                                                    CategorieproduitViewSDO.class);
    }

    /**
     * getCategorieunitemesureView1: generated method. Do not modify.
     */
    public CategorieunitemesureViewSDO getCategorieunitemesureView1(BigDecimal idcategorieunitemesure) throws ServiceException {
        return (CategorieunitemesureViewSDO) get(new Object[] { idcategorieunitemesure }, "CategorieunitemesureView1",
                                                 CategorieunitemesureViewSDO.class);
    }

    /**
     * findCategorieunitemesureView1: generated method. Do not modify.
     */
    public List<CategorieunitemesureViewSDO> findCategorieunitemesureView1(FindCriteria findCriteria,
                                                                           FindControl findControl) throws ServiceException {
        return (List<CategorieunitemesureViewSDO>) find(findCriteria, findControl, "CategorieunitemesureView1",
                                                        CategorieunitemesureViewSDO.class);
    }

    /**
     * getCertificatorigineView1: generated method. Do not modify.
     */
    public CertificatorigineViewSDO getCertificatorigineView1(BigDecimal idcertificatorigine) throws ServiceException {
        return (CertificatorigineViewSDO) get(new Object[] { idcertificatorigine }, "CertificatorigineView1",
                                              CertificatorigineViewSDO.class);
    }

    /**
     * findCertificatorigineView1: generated method. Do not modify.
     */
    public List<CertificatorigineViewSDO> findCertificatorigineView1(FindCriteria findCriteria,
                                                                     FindControl findControl) throws ServiceException {
        return (List<CertificatorigineViewSDO>) find(findCriteria, findControl, "CertificatorigineView1",
                                                     CertificatorigineViewSDO.class);
    }

    /**
     * getCollectepfnlView1: generated method. Do not modify.
     */
    public CollectepfnlViewSDO getCollectepfnlView1(BigDecimal idcollectepfnl) throws ServiceException {
        return (CollectepfnlViewSDO) get(new Object[] { idcollectepfnl }, "CollectepfnlView1",
                                         CollectepfnlViewSDO.class);
    }

    /**
     * findCollectepfnlView1: generated method. Do not modify.
     */
    public List<CollectepfnlViewSDO> findCollectepfnlView1(FindCriteria findCriteria,
                                                           FindControl findControl) throws ServiceException {
        return (List<CollectepfnlViewSDO>) find(findCriteria, findControl, "CollectepfnlView1",
                                                CollectepfnlViewSDO.class);
    }

    /**
     * getCommuneView1: generated method. Do not modify.
     */
    public CommuneViewSDO getCommuneView1(BigDecimal idcommunes) throws ServiceException {
        return (CommuneViewSDO) get(new Object[] { idcommunes }, "CommuneView1", CommuneViewSDO.class);
    }

    /**
     * findCommuneView1: generated method. Do not modify.
     */
    public List<CommuneViewSDO> findCommuneView1(FindCriteria findCriteria,
                                                 FindControl findControl) throws ServiceException {
        return (List<CommuneViewSDO>) find(findCriteria, findControl, "CommuneView1", CommuneViewSDO.class);
    }

    /**
     * getDepartementView1: generated method. Do not modify.
     */
    public DepartementViewSDO getDepartementView1(BigDecimal iddepartements) throws ServiceException {
        return (DepartementViewSDO) get(new Object[] { iddepartements }, "DepartementView1", DepartementViewSDO.class);
    }

    /**
     * findDepartementView1: generated method. Do not modify.
     */
    public List<DepartementViewSDO> findDepartementView1(FindCriteria findCriteria,
                                                         FindControl findControl) throws ServiceException {
        return (List<DepartementViewSDO>) find(findCriteria, findControl, "DepartementView1", DepartementViewSDO.class);
    }

    /**
     * getDetailpermisView1: generated method. Do not modify.
     */
    public DetailpermisViewSDO getDetailpermisView1(BigDecimal iddetailpermis) throws ServiceException {
        return (DetailpermisViewSDO) get(new Object[] { iddetailpermis }, "DetailpermisView1",
                                         DetailpermisViewSDO.class);
    }

    /**
     * findDetailpermisView1: generated method. Do not modify.
     */
    public List<DetailpermisViewSDO> findDetailpermisView1(FindCriteria findCriteria,
                                                           FindControl findControl) throws ServiceException {
        return (List<DetailpermisViewSDO>) find(findCriteria, findControl, "DetailpermisView1",
                                                DetailpermisViewSDO.class);
    }

    /**
     * getDetailscollectepfnlView1: generated method. Do not modify.
     */
    public DetailscollectepfnlViewSDO getDetailscollectepfnlView1(BigDecimal iddetailscollectepfnl) throws ServiceException {
        return (DetailscollectepfnlViewSDO) get(new Object[] { iddetailscollectepfnl }, "DetailscollectepfnlView1",
                                                DetailscollectepfnlViewSDO.class);
    }

    /**
     * findDetailscollectepfnlView1: generated method. Do not modify.
     */
    public List<DetailscollectepfnlViewSDO> findDetailscollectepfnlView1(FindCriteria findCriteria,
                                                                         FindControl findControl) throws ServiceException {
        return (List<DetailscollectepfnlViewSDO>) find(findCriteria, findControl, "DetailscollectepfnlView1",
                                                       DetailscollectepfnlViewSDO.class);
    }

    /**
     * getDetailsexportpfnlView1: generated method. Do not modify.
     */
    public DetailsexportpfnlViewSDO getDetailsexportpfnlView1(BigDecimal iddetailsexportpfnl) throws ServiceException {
        return (DetailsexportpfnlViewSDO) get(new Object[] { iddetailsexportpfnl }, "DetailsexportpfnlView1",
                                              DetailsexportpfnlViewSDO.class);
    }

    /**
     * findDetailsexportpfnlView1: generated method. Do not modify.
     */
    public List<DetailsexportpfnlViewSDO> findDetailsexportpfnlView1(FindCriteria findCriteria,
                                                                     FindControl findControl) throws ServiceException {
        return (List<DetailsexportpfnlViewSDO>) find(findCriteria, findControl, "DetailsexportpfnlView1",
                                                     DetailsexportpfnlViewSDO.class);
    }

    /**
     * getExportpfnlView1: generated method. Do not modify.
     */
    public ExportpfnlViewSDO getExportpfnlView1(BigDecimal idexportpfnl) throws ServiceException {
        return (ExportpfnlViewSDO) get(new Object[] { idexportpfnl }, "ExportpfnlView1", ExportpfnlViewSDO.class);
    }

    /**
     * findExportpfnlView1: generated method. Do not modify.
     */
    public List<ExportpfnlViewSDO> findExportpfnlView1(FindCriteria findCriteria,
                                                       FindControl findControl) throws ServiceException {
        return (List<ExportpfnlViewSDO>) find(findCriteria, findControl, "ExportpfnlView1", ExportpfnlViewSDO.class);
    }

    /**
     * getFamillePfnlView1: generated method. Do not modify.
     */
    public FamillePfnlViewSDO getFamillePfnlView1(BigDecimal idfamillepfnl) throws ServiceException {
        return (FamillePfnlViewSDO) get(new Object[] { idfamillepfnl }, "FamillePfnlView1", FamillePfnlViewSDO.class);
    }

    /**
     * findFamillePfnlView1: generated method. Do not modify.
     */
    public List<FamillePfnlViewSDO> findFamillePfnlView1(FindCriteria findCriteria,
                                                         FindControl findControl) throws ServiceException {
        return (List<FamillePfnlViewSDO>) find(findCriteria, findControl, "FamillePfnlView1", FamillePfnlViewSDO.class);
    }

    /**
     * getLettrevoitureView1: generated method. Do not modify.
     */
    public LettrevoitureViewSDO getLettrevoitureView1(BigDecimal idlettrevoiture) throws ServiceException {
        return (LettrevoitureViewSDO) get(new Object[] { idlettrevoiture }, "LettrevoitureView1",
                                          LettrevoitureViewSDO.class);
    }

    /**
     * findLettrevoitureView1: generated method. Do not modify.
     */
    public List<LettrevoitureViewSDO> findLettrevoitureView1(FindCriteria findCriteria,
                                                             FindControl findControl) throws ServiceException {
        return (List<LettrevoitureViewSDO>) find(findCriteria, findControl, "LettrevoitureView1",
                                                 LettrevoitureViewSDO.class);
    }

    /**
     * getLocaliteView1: generated method. Do not modify.
     */
    public LocaliteViewSDO getLocaliteView1(BigDecimal idlocalite) throws ServiceException {
        return (LocaliteViewSDO) get(new Object[] { idlocalite }, "LocaliteView1", LocaliteViewSDO.class);
    }

    /**
     * findLocaliteView1: generated method. Do not modify.
     */
    public List<LocaliteViewSDO> findLocaliteView1(FindCriteria findCriteria,
                                                   FindControl findControl) throws ServiceException {
        return (List<LocaliteViewSDO>) find(findCriteria, findControl, "LocaliteView1", LocaliteViewSDO.class);
    }

    /**
     * getOriginespnflsView1: generated method. Do not modify.
     */
    public OriginespnflsViewSDO getOriginespnflsView1(BigDecimal idoriginespnfls) throws ServiceException {
        return (OriginespnflsViewSDO) get(new Object[] { idoriginespnfls }, "OriginespnflsView1",
                                          OriginespnflsViewSDO.class);
    }

    /**
     * findOriginespnflsView1: generated method. Do not modify.
     */
    public List<OriginespnflsViewSDO> findOriginespnflsView1(FindCriteria findCriteria,
                                                             FindControl findControl) throws ServiceException {
        return (List<OriginespnflsViewSDO>) find(findCriteria, findControl, "OriginespnflsView1",
                                                 OriginespnflsViewSDO.class);
    }

    /**
     * getPartiesProduitsPfnlView1: generated method. Do not modify.
     */
    public PartiesProduitsPfnlViewSDO getPartiesProduitsPfnlView1(BigDecimal idpartiesproduitspfnl) throws ServiceException {
        return (PartiesProduitsPfnlViewSDO) get(new Object[] { idpartiesproduitspfnl }, "PartiesProduitsPfnlView1",
                                                PartiesProduitsPfnlViewSDO.class);
    }

    /**
     * findPartiesProduitsPfnlView1: generated method. Do not modify.
     */
    public List<PartiesProduitsPfnlViewSDO> findPartiesProduitsPfnlView1(FindCriteria findCriteria,
                                                                         FindControl findControl) throws ServiceException {
        return (List<PartiesProduitsPfnlViewSDO>) find(findCriteria, findControl, "PartiesProduitsPfnlView1",
                                                       PartiesProduitsPfnlViewSDO.class);
    }

    /**
     * getPartiesRecolteesView1: generated method. Do not modify.
     */
    public PartiesRecolteesViewSDO getPartiesRecolteesView1(BigDecimal idpartiesrecoltees) throws ServiceException {
        return (PartiesRecolteesViewSDO) get(new Object[] { idpartiesrecoltees }, "PartiesRecolteesView1",
                                             PartiesRecolteesViewSDO.class);
    }

    /**
     * findPartiesRecolteesView1: generated method. Do not modify.
     */
    public List<PartiesRecolteesViewSDO> findPartiesRecolteesView1(FindCriteria findCriteria,
                                                                   FindControl findControl) throws ServiceException {
        return (List<PartiesRecolteesViewSDO>) find(findCriteria, findControl, "PartiesRecolteesView1",
                                                    PartiesRecolteesViewSDO.class);
    }

    /**
     * getPartiproduit1: generated method. Do not modify.
     */
    public PartiproduitSDO getPartiproduit1(BigDecimal idpartiesproduitspfnl) throws ServiceException {
        return (PartiproduitSDO) get(new Object[] { idpartiesproduitspfnl }, "Partiproduit1", PartiproduitSDO.class);
    }

    /**
     * findPartiproduit1: generated method. Do not modify.
     */
    public List<PartiproduitSDO> findPartiproduit1(FindCriteria findCriteria,
                                                   FindControl findControl) throws ServiceException {
        return (List<PartiproduitSDO>) find(findCriteria, findControl, "Partiproduit1", PartiproduitSDO.class);
    }

    /**
     * getPaysView1: generated method. Do not modify.
     */
    public PaysViewSDO getPaysView1(BigDecimal idpays) throws ServiceException {
        return (PaysViewSDO) get(new Object[] { idpays }, "PaysView1", PaysViewSDO.class);
    }

    /**
     * findPaysView1: generated method. Do not modify.
     */
    public List<PaysViewSDO> findPaysView1(FindCriteria findCriteria, FindControl findControl) throws ServiceException {
        return (List<PaysViewSDO>) find(findCriteria, findControl, "PaysView1", PaysViewSDO.class);
    }

    /**
     * getPermisView1: generated method. Do not modify.
     */
    public PermisViewSDO getPermisView1(BigDecimal idpermis) throws ServiceException {
        return (PermisViewSDO) get(new Object[] { idpermis }, "PermisView1", PermisViewSDO.class);
    }

    /**
     * findPermisView1: generated method. Do not modify.
     */
    public List<PermisViewSDO> findPermisView1(FindCriteria findCriteria,
                                               FindControl findControl) throws ServiceException {
        return (List<PermisViewSDO>) find(findCriteria, findControl, "PermisView1", PermisViewSDO.class);
    }

    /**
     * getPermissionnairespnflView1: generated method. Do not modify.
     */
    public PermissionnairespnflViewSDO getPermissionnairespnflView1(BigDecimal idpermissionnairespnfl) throws ServiceException {
        return (PermissionnairespnflViewSDO) get(new Object[] { idpermissionnairespnfl }, "PermissionnairespnflView1",
                                                 PermissionnairespnflViewSDO.class);
    }

    /**
     * findPermissionnairespnflView1: generated method. Do not modify.
     */
    public List<PermissionnairespnflViewSDO> findPermissionnairespnflView1(FindCriteria findCriteria,
                                                                           FindControl findControl) throws ServiceException {
        return (List<PermissionnairespnflViewSDO>) find(findCriteria, findControl, "PermissionnairespnflView1",
                                                        PermissionnairespnflViewSDO.class);
    }

    /**
     * getPostecontroleView1: generated method. Do not modify.
     */
    public PostecontroleViewSDO getPostecontroleView1(BigDecimal idpostecontrole) throws ServiceException {
        return (PostecontroleViewSDO) get(new Object[] { idpostecontrole }, "PostecontroleView1",
                                          PostecontroleViewSDO.class);
    }

    /**
     * findPostecontroleView1: generated method. Do not modify.
     */
    public List<PostecontroleViewSDO> findPostecontroleView1(FindCriteria findCriteria,
                                                             FindControl findControl) throws ServiceException {
        return (List<PostecontroleViewSDO>) find(findCriteria, findControl, "PostecontroleView1",
                                                 PostecontroleViewSDO.class);
    }

    /**
     * getProduitsPfnlView1: generated method. Do not modify.
     */
    public ProduitsPfnlViewSDO getProduitsPfnlView1(BigDecimal idproduitspfnl) throws ServiceException {
        return (ProduitsPfnlViewSDO) get(new Object[] { idproduitspfnl }, "ProduitsPfnlView1",
                                         ProduitsPfnlViewSDO.class);
    }

    /**
     * findProduitsPfnlView1: generated method. Do not modify.
     */
    public List<ProduitsPfnlViewSDO> findProduitsPfnlView1(FindCriteria findCriteria,
                                                           FindControl findControl) throws ServiceException {
        return (List<ProduitsPfnlViewSDO>) find(findCriteria, findControl, "ProduitsPfnlView1",
                                                ProduitsPfnlViewSDO.class);
    }

    /**
     * getRegionView1: generated method. Do not modify.
     */
    public RegionViewSDO getRegionView1(BigDecimal idregions) throws ServiceException {
        return (RegionViewSDO) get(new Object[] { idregions }, "RegionView1", RegionViewSDO.class);
    }

    /**
     * findRegionView1: generated method. Do not modify.
     */
    public List<RegionViewSDO> findRegionView1(FindCriteria findCriteria,
                                               FindControl findControl) throws ServiceException {
        return (List<RegionViewSDO>) find(findCriteria, findControl, "RegionView1", RegionViewSDO.class);
    }

    /**
     * getRegionsView1: generated method. Do not modify.
     */
    public RegionsViewSDO getRegionsView1(BigDecimal idregions) throws ServiceException {
        return (RegionsViewSDO) get(new Object[] { idregions }, "RegionsView1", RegionsViewSDO.class);
    }

    /**
     * findRegionsView1: generated method. Do not modify.
     */
    public List<RegionsViewSDO> findRegionsView1(FindCriteria findCriteria,
                                                 FindControl findControl) throws ServiceException {
        return (List<RegionsViewSDO>) find(findCriteria, findControl, "RegionsView1", RegionsViewSDO.class);
    }

    /**
     * getUnitemesureView1: generated method. Do not modify.
     */
    public UnitemesureViewSDO getUnitemesureView1(BigDecimal idunitemesure) throws ServiceException {
        return (UnitemesureViewSDO) get(new Object[] { idunitemesure }, "UnitemesureView1", UnitemesureViewSDO.class);
    }

    /**
     * findUnitemesureView1: generated method. Do not modify.
     */
    public List<UnitemesureViewSDO> findUnitemesureView1(FindCriteria findCriteria,
                                                         FindControl findControl) throws ServiceException {
        return (List<UnitemesureViewSDO>) find(findCriteria, findControl, "UnitemesureView1", UnitemesureViewSDO.class);
    }
}

