package cm.gov.minfof.model.entity.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 10 14:41:25 CET 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void changepwd(BigDecimal bd, String pwd);

    void modifuser(BigDecimal bd, String nuser, String puser, String muser);
}

