package cm.gov.minfof.model.entityviewobject.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 22 15:09:45 WAT 2016
// ---------------------------------------------------------------------
public interface CollectepfnlViewRow extends Row {
    BigDecimal getIdcollectepfnl();

    void setIdcollectepfnl(BigDecimal value);

    Timestamp getDatecollecte();

    void setDatecollecte(Timestamp value);

    String getIdentificateur();

    void setIdentificateur(String value);

    BigDecimal getIddepartement();

    void setIddepartement(BigDecimal value);


    BigDecimal getIdlocalite();

    void setIdlocalite(BigDecimal value);
}

