package cm.gov.minfof.model.entityviewobject.common;

import java.sql.Timestamp;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 03:15:42 WAT 2016
// ---------------------------------------------------------------------
public interface CollectepfnlView extends ViewObject {
    void setdateDebut(Timestamp value);

    void setdateFin(Timestamp value);
}

