package cm.gov.minfof.model.entityviewobject.common;

import java.sql.Timestamp;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 24 07:51:23 WAT 2016
// ---------------------------------------------------------------------
public interface PermisView extends ViewObject {
    void setDebut(Timestamp value);

    void setFin(Timestamp value);
}

