package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 17 10:17:17 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CategorieunitemesureDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CategorieunitemesureDefImpl() {
    }
}

