package cm.gov.minfof.model.entity;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 11 08:12:43 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CertificatorigineImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idcertificatorigine,
        Quantite,
        Idpartieproduitpfnl,
        Idunitemesure,
        Numeroco,
        Destinataire,
        Idpermis,
        Idpays,
        Certificatorigine,
        IdunitemesureCertificatorigine,
        Certificatorigine1,
        IdpartieproduitpfnlCertificatorigine,
        Certificatorigine2,
        IdpermisCertificatorigine,
        Permis;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDCERTIFICATORIGINE = AttributesEnum.Idcertificatorigine.index();
    public static final int QUANTITE = AttributesEnum.Quantite.index();
    public static final int IDPARTIEPRODUITPFNL = AttributesEnum.Idpartieproduitpfnl.index();
    public static final int IDUNITEMESURE = AttributesEnum.Idunitemesure.index();
    public static final int NUMEROCO = AttributesEnum.Numeroco.index();
    public static final int DESTINATAIRE = AttributesEnum.Destinataire.index();
    public static final int IDPERMIS = AttributesEnum.Idpermis.index();
    public static final int IDPAYS = AttributesEnum.Idpays.index();
    public static final int CERTIFICATORIGINE = AttributesEnum.Certificatorigine.index();
    public static final int IDUNITEMESURECERTIFICATORIGINE = AttributesEnum.IdunitemesureCertificatorigine.index();
    public static final int CERTIFICATORIGINE1 = AttributesEnum.Certificatorigine1.index();
    public static final int IDPARTIEPRODUITPFNLCERTIFICATORIGINE =
        AttributesEnum.IdpartieproduitpfnlCertificatorigine.index();
    public static final int CERTIFICATORIGINE2 = AttributesEnum.Certificatorigine2.index();
    public static final int IDPERMISCERTIFICATORIGINE = AttributesEnum.IdpermisCertificatorigine.index();
    public static final int PERMIS = AttributesEnum.Permis.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CertificatorigineImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("cm.gov.minfof.model.entity.Certificatorigine");
    }

    /**
     * Gets the attribute value for Idcertificatorigine, using the alias name Idcertificatorigine.
     * @return the value of Idcertificatorigine
     */
    public BigDecimal getIdcertificatorigine() {
        return (BigDecimal) getAttributeInternal(IDCERTIFICATORIGINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idcertificatorigine.
     * @param value value to set the Idcertificatorigine
     */
    public void setIdcertificatorigine(BigDecimal value) {
        setAttributeInternal(IDCERTIFICATORIGINE, value);
    }

    /**
     * Gets the attribute value for Quantite, using the alias name Quantite.
     * @return the value of Quantite
     */
    public Float getQuantite() {
        return (Float) getAttributeInternal(QUANTITE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantite.
     * @param value value to set the Quantite
     */
    public void setQuantite(Float value) {
        setAttributeInternal(QUANTITE, value);
    }

    /**
     * Gets the attribute value for Idpartieproduitpfnl, using the alias name Idpartieproduitpfnl.
     * @return the value of Idpartieproduitpfnl
     */
    public BigDecimal getIdpartieproduitpfnl() {
        return (BigDecimal) getAttributeInternal(IDPARTIEPRODUITPFNL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idpartieproduitpfnl.
     * @param value value to set the Idpartieproduitpfnl
     */
    public void setIdpartieproduitpfnl(BigDecimal value) {
        setAttributeInternal(IDPARTIEPRODUITPFNL, value);
    }

    /**
     * Gets the attribute value for Idunitemesure, using the alias name Idunitemesure.
     * @return the value of Idunitemesure
     */
    public BigDecimal getIdunitemesure() {
        return (BigDecimal) getAttributeInternal(IDUNITEMESURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idunitemesure.
     * @param value value to set the Idunitemesure
     */
    public void setIdunitemesure(BigDecimal value) {
        setAttributeInternal(IDUNITEMESURE, value);
    }

    /**
     * Gets the attribute value for Numeroco, using the alias name Numeroco.
     * @return the value of Numeroco
     */
    public String getNumeroco() {
        return (String) getAttributeInternal(NUMEROCO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Numeroco.
     * @param value value to set the Numeroco
     */
    public void setNumeroco(String value) {
        setAttributeInternal(NUMEROCO, value);
    }

    /**
     * Gets the attribute value for Destinataire, using the alias name Destinataire.
     * @return the value of Destinataire
     */
    public String getDestinataire() {
        return (String) getAttributeInternal(DESTINATAIRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Destinataire.
     * @param value value to set the Destinataire
     */
    public void setDestinataire(String value) {
        setAttributeInternal(DESTINATAIRE, value);
    }

    /**
     * Gets the attribute value for Idpermis, using the alias name Idpermis.
     * @return the value of Idpermis
     */
    public BigDecimal getIdpermis() {
        return (BigDecimal) getAttributeInternal(IDPERMIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idpermis.
     * @param value value to set the Idpermis
     */
    public void setIdpermis(BigDecimal value) {
        setAttributeInternal(IDPERMIS, value);
    }

    /**
     * Gets the attribute value for Idpays, using the alias name Idpays.
     * @return the value of Idpays
     */
    public BigDecimal getIdpays() {
        return (BigDecimal) getAttributeInternal(IDPAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idpays.
     * @param value value to set the Idpays
     */
    public void setIdpays(BigDecimal value) {
        setAttributeInternal(IDPAYS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCertificatorigine() {
        return (RowIterator) getAttributeInternal(CERTIFICATORIGINE);
    }

    /**
     * @return the associated entity CertificatorigineImpl.
     */
    public CertificatorigineImpl getIdunitemesureCertificatorigine() {
        return (CertificatorigineImpl) getAttributeInternal(IDUNITEMESURECERTIFICATORIGINE);
    }

    /**
     * Sets <code>value</code> as the associated entity CertificatorigineImpl.
     */
    public void setIdunitemesureCertificatorigine(CertificatorigineImpl value) {
        setAttributeInternal(IDUNITEMESURECERTIFICATORIGINE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCertificatorigine1() {
        return (RowIterator) getAttributeInternal(CERTIFICATORIGINE1);
    }

    /**
     * @return the associated entity CertificatorigineImpl.
     */
    public CertificatorigineImpl getIdpartieproduitpfnlCertificatorigine() {
        return (CertificatorigineImpl) getAttributeInternal(IDPARTIEPRODUITPFNLCERTIFICATORIGINE);
    }

    /**
     * Sets <code>value</code> as the associated entity CertificatorigineImpl.
     */
    public void setIdpartieproduitpfnlCertificatorigine(CertificatorigineImpl value) {
        setAttributeInternal(IDPARTIEPRODUITPFNLCERTIFICATORIGINE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCertificatorigine2() {
        return (RowIterator) getAttributeInternal(CERTIFICATORIGINE2);
    }

    /**
     * @return the associated entity CertificatorigineImpl.
     */
    public CertificatorigineImpl getIdpermisCertificatorigine() {
        return (CertificatorigineImpl) getAttributeInternal(IDPERMISCERTIFICATORIGINE);
    }

    /**
     * Sets <code>value</code> as the associated entity CertificatorigineImpl.
     */
    public void setIdpermisCertificatorigine(CertificatorigineImpl value) {
        setAttributeInternal(IDPERMISCERTIFICATORIGINE, value);
    }

    /**
     * @return the associated entity PermisImpl.
     */
    public PermisImpl getPermis() {
        return (PermisImpl) getAttributeInternal(PERMIS);
    }

    /**
     * Sets <code>value</code> as the associated entity PermisImpl.
     */
    public void setPermis(PermisImpl value) {
        setAttributeInternal(PERMIS, value);
    }


    /**
     * @param idcertificatorigine key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal idcertificatorigine) {
        return new Key(new Object[] { idcertificatorigine });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            System.out.println("Avant insertion");
            BigDecimal id = getLastId("getLastidCoView1");
            this.setIdcertificatorigine(id);
        }
        super.doDML(operation, e);
    }
    
    public BigDecimal getLastId(String viewName) {
        BigDecimal lastId = new BigDecimal(0);
        ViewObject vo = this.getDBTransaction()
                            .getRootApplicationModule()
                            .findViewObject(viewName);
        vo.executeQuery();
        if (vo.hasNext()) {
            //System.out.println("entree dans la condition hasNext");
            Row r = vo.next();
            //System.out.println("row = " + r);
            lastId = (BigDecimal) r.getAttribute(0);
        }
        BigDecimal un = new BigDecimal(1);
        lastId = lastId.add(un);
        return lastId; 
    }
}

