package cm.gov.minfof.model.entity;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 27 19:02:23 WAT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class departementNonFiltreRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Iddepartements,
        Nomdepartement,
        Codedepartement,
        Idregions,
        Nomcheflieu;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDDEPARTEMENTS = AttributesEnum.Iddepartements.index();
    public static final int NOMDEPARTEMENT = AttributesEnum.Nomdepartement.index();
    public static final int CODEDEPARTEMENT = AttributesEnum.Codedepartement.index();
    public static final int IDREGIONS = AttributesEnum.Idregions.index();
    public static final int NOMCHEFLIEU = AttributesEnum.Nomcheflieu.index();

    /**
     * This is the default constructor (do not remove).
     */
    public departementNonFiltreRowImpl() {
    }
}

