package cm.gov.minfof.model.entity;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 27 19:03:07 WAT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class departementNonFiltreImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public departementNonFiltreImpl() {
    }
}

