package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 31 09:20:09 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupeutilisateurDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GroupeutilisateurDefImpl() {
    }
}

