package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 10 23:03:19 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OriginespnflsCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public OriginespnflsCollImpl() {
    }
}

