package cm.gov.minfof.model.entity;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 19 18:19:28 WAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartiesProduitPfnlCompletImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PartiesProduitPfnlCompletImpl() {
    }
}

