package cm.gov.minfof.model.entity;

import cm.gov.minfof.model.entityviewobject.VueImplementation;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 21 15:01:48 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartiesRecolteesViewImpl extends VueImplementation {
    /**
     * This is the default constructor (do not remove).
     */
    public PartiesRecolteesViewImpl() {
    }
}

