package cm.gov.minfof.model.entity;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 19 18:19:24 WAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartiesProduitPfnlCompletRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idpartiesproduitspfnl,
        Idpartiesrecoltees,
        Idproduitspfnl,
        Idunitemesure,
        Idunitemesureexport,
        Idproduitspfnl1,
        Nomscientifique,
        Nomcommercial,
        Codeproduit,
        Idfamillepfnl,
        Descriptionsommaire,
        Modeattribution,
        Idcategorie,
        Idpartiesrecoltees1,
        Nompartierecoltee;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDPARTIESPRODUITSPFNL = AttributesEnum.Idpartiesproduitspfnl.index();
    public static final int IDPARTIESRECOLTEES = AttributesEnum.Idpartiesrecoltees.index();
    public static final int IDPRODUITSPFNL = AttributesEnum.Idproduitspfnl.index();
    public static final int IDUNITEMESURE = AttributesEnum.Idunitemesure.index();
    public static final int IDUNITEMESUREEXPORT = AttributesEnum.Idunitemesureexport.index();
    public static final int IDPRODUITSPFNL1 = AttributesEnum.Idproduitspfnl1.index();
    public static final int NOMSCIENTIFIQUE = AttributesEnum.Nomscientifique.index();
    public static final int NOMCOMMERCIAL = AttributesEnum.Nomcommercial.index();
    public static final int CODEPRODUIT = AttributesEnum.Codeproduit.index();
    public static final int IDFAMILLEPFNL = AttributesEnum.Idfamillepfnl.index();
    public static final int DESCRIPTIONSOMMAIRE = AttributesEnum.Descriptionsommaire.index();
    public static final int MODEATTRIBUTION = AttributesEnum.Modeattribution.index();
    public static final int IDCATEGORIE = AttributesEnum.Idcategorie.index();
    public static final int IDPARTIESRECOLTEES1 = AttributesEnum.Idpartiesrecoltees1.index();
    public static final int NOMPARTIERECOLTEE = AttributesEnum.Nompartierecoltee.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PartiesProduitPfnlCompletRowImpl() {
    }
}

