package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 10 03:41:42 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaysDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PaysDefImpl() {
    }
}

