package cm.gov.minfof.model.entity;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 10 03:41:41 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaysImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idpays,
        Nompays,
        Codepays;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDPAYS = AttributesEnum.Idpays.index();
    public static final int NOMPAYS = AttributesEnum.Nompays.index();
    public static final int CODEPAYS = AttributesEnum.Codepays.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PaysImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("cm.gov.minfof.model.entity.Pays");
    }


    /**
     * Gets the attribute value for Idpays, using the alias name Idpays.
     * @return the value of Idpays
     */
    public BigDecimal getIdpays() {
        return (BigDecimal) getAttributeInternal(IDPAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idpays.
     * @param value value to set the Idpays
     */
    public void setIdpays(BigDecimal value) {
        setAttributeInternal(IDPAYS, value);
    }

    /**
     * Gets the attribute value for Nompays, using the alias name Nompays.
     * @return the value of Nompays
     */
    public String getNompays() {
        return (String) getAttributeInternal(NOMPAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nompays.
     * @param value value to set the Nompays
     */
    public void setNompays(String value) {
        setAttributeInternal(NOMPAYS, value);
    }


    /**
     * Gets the attribute value for Codepays, using the alias name Codepays.
     * @return the value of Codepays
     */
    public String getCodepays() {
        return (String) getAttributeInternal(CODEPAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Codepays.
     * @param value value to set the Codepays
     */
    public void setCodepays(String value) {
        setAttributeInternal(CODEPAYS, value);
    }


    /**
     * @param idpays key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal idpays) {
        return new Key(new Object[] { idpays });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT)
        {
            BigDecimal id = getLastId("getLastIdPays1");
            setIdpays(id);
        }
        super.doDML(operation, e);
    }
    
    public BigDecimal getLastId(String viewName)
    {
        BigDecimal lastId=new BigDecimal(0);
        ViewObject vo = this.getDBTransaction()
                            .getRootApplicationModule()
                            .findViewObject(viewName);
        vo.executeQuery();
        if (vo.hasNext())
        {
            Row r = vo.next();
            lastId = (BigDecimal) r.getAttribute(0);
        }
        BigDecimal un = new BigDecimal(1);
        lastId = lastId.add(un);
        return lastId; 
    }
}

