package cm.gov.minfof.model.entity;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 20 04:12:13 WAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PermissionnaireEtPermisFinalImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PermissionnaireEtPermisFinalImpl() {
    }
}

