package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 12 15:29:45 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PermissionnairespnflCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public PermissionnairespnflCollImpl() {
    }
}

