package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 18 13:11:43 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostecontroleDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PostecontroleDefImpl() {
    }
}

