package cm.gov.minfof.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 06 08:39:28 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProduitsPfnlDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProduitsPfnlDefImpl() {
    }
}

