package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 22 05:15:55 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CollMultiCritereImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CollMultiCritereImpl() {
    }
}

