package cm.gov.minfof.model.entityviewobject;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 21 12:46:10 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommuneViewImpl extends VueImplementation {
    /**
     * This is the default constructor (do not remove).
     */
    public CommuneViewImpl() {
    }

    /**
     * Returns the variable value for idDepartementBind.
     * @return variable value for idDepartementBind
     */
    public BigDecimal getidDepartementBind() {
        return (BigDecimal) ensureVariableManager().getVariableValue("idDepartementBind");
    }

    /**
     * Sets <code>value</code> for variable idDepartementBind.
     * @param value value to bind as idDepartementBind
     */
    public void setidDepartementBind(BigDecimal value) {
        ensureVariableManager().setVariableValue("idDepartementBind", value);
    }
}

