package cm.gov.minfof.model.entityviewobject;

import cm.gov.minfof.model.entity.DetailpermisImpl;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 04 21:33:44 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailpermisViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DETAILPERMIS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Iddetailpermis,
        Quantite,
        Idunitemesure,
        Idpermis,
        Observation,
        Idpartieproduitpfnl,
        Idregions,
        idunitemesureconsultation,
        DetailpermisView,
        DetailpermisView1,
        DetailpermisView2,
        PermisView,
        UnitemesureView1,
        PermisView1,
        PartiesproduitspfnlView1,
        getLibelleProduitComplet1,
        AppModule_RegionView1_1,
        AppModule_UniteMesureWithPartieProduitPfnl1_1,
        UniteMesureWithPartieProduitPfnl1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDDETAILPERMIS = AttributesEnum.Iddetailpermis.index();
    public static final int QUANTITE = AttributesEnum.Quantite.index();
    public static final int IDUNITEMESURE = AttributesEnum.Idunitemesure.index();
    public static final int IDPERMIS = AttributesEnum.Idpermis.index();
    public static final int OBSERVATION = AttributesEnum.Observation.index();
    public static final int IDPARTIEPRODUITPFNL = AttributesEnum.Idpartieproduitpfnl.index();
    public static final int IDREGIONS = AttributesEnum.Idregions.index();
    public static final int IDUNITEMESURECONSULTATION = AttributesEnum.idunitemesureconsultation.index();
    public static final int DETAILPERMISVIEW = AttributesEnum.DetailpermisView.index();
    public static final int DETAILPERMISVIEW1 = AttributesEnum.DetailpermisView1.index();
    public static final int DETAILPERMISVIEW2 = AttributesEnum.DetailpermisView2.index();
    public static final int PERMISVIEW = AttributesEnum.PermisView.index();
    public static final int UNITEMESUREVIEW1 = AttributesEnum.UnitemesureView1.index();
    public static final int PERMISVIEW1 = AttributesEnum.PermisView1.index();
    public static final int PARTIESPRODUITSPFNLVIEW1 = AttributesEnum.PartiesproduitspfnlView1.index();
    public static final int GETLIBELLEPRODUITCOMPLET1 = AttributesEnum.getLibelleProduitComplet1.index();
    public static final int APPMODULE_REGIONVIEW1_1 = AttributesEnum.AppModule_RegionView1_1.index();
    public static final int APPMODULE_UNITEMESUREWITHPARTIEPRODUITPFNL1_1 =
        AttributesEnum.AppModule_UniteMesureWithPartieProduitPfnl1_1.index();
    public static final int UNITEMESUREWITHPARTIEPRODUITPFNL1 =
        AttributesEnum.UniteMesureWithPartieProduitPfnl1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailpermisViewRowImpl() {
    }

    /**
     * Gets Detailpermis entity object.
     * @return the Detailpermis
     */
    public DetailpermisImpl getDetailpermis() {
        return (DetailpermisImpl) getEntity(ENTITY_DETAILPERMIS);
    }

    /**
     * Gets the attribute value for iddetailpermis using the alias name Iddetailpermis.
     * @return the iddetailpermis
     */
    public BigDecimal getIddetailpermis() {
        return (BigDecimal) getAttributeInternal(IDDETAILPERMIS);
    }

    /**
     * Sets <code>value</code> as attribute value for iddetailpermis using the alias name Iddetailpermis.
     * @param value value to set the iddetailpermis
     */
    public void setIddetailpermis(BigDecimal value) {
        setAttributeInternal(IDDETAILPERMIS, value);
    }

    /**
     * Gets the attribute value for quantite using the alias name Quantite.
     * @return the quantite
     */
    public Float getQuantite() {
        return (Float) getAttributeInternal(QUANTITE);
    }

    /**
     * Sets <code>value</code> as attribute value for quantite using the alias name Quantite.
     * @param value value to set the quantite
     */
    public void setQuantite(Float value) {
        setAttributeInternal(QUANTITE, value);
    }

    /**
     * Gets the attribute value for idunitemesure using the alias name Idunitemesure.
     * @return the idunitemesure
     */
    public BigDecimal getIdunitemesure() {
        return (BigDecimal) getAttributeInternal(IDUNITEMESURE);
    }

    /**
     * Sets <code>value</code> as attribute value for idunitemesure using the alias name Idunitemesure.
     * @param value value to set the idunitemesure
     */
    public void setIdunitemesure(BigDecimal value) {
        setAttributeInternal(IDUNITEMESURE, value);
    }

    /**
     * Gets the attribute value for idpermis using the alias name Idpermis.
     * @return the idpermis
     */
    public BigDecimal getIdpermis() {
        return (BigDecimal) getAttributeInternal(IDPERMIS);
    }

    /**
     * Sets <code>value</code> as attribute value for idpermis using the alias name Idpermis.
     * @param value value to set the idpermis
     */
    public void setIdpermis(BigDecimal value) {
        setAttributeInternal(IDPERMIS, value);
    }

    /**
     * Gets the attribute value for observation using the alias name Observation.
     * @return the observation
     */
    public String getObservation() {
        return (String) getAttributeInternal(OBSERVATION);
    }

    /**
     * Sets <code>value</code> as attribute value for observation using the alias name Observation.
     * @param value value to set the observation
     */
    public void setObservation(String value) {
        setAttributeInternal(OBSERVATION, value);
    }

    /**
     * Gets the attribute value for idpartieproduitpfnl using the alias name Idpartieproduitpfnl.
     * @return the idpartieproduitpfnl
     */
    public BigDecimal getIdpartieproduitpfnl() {
        return (BigDecimal) getAttributeInternal(IDPARTIEPRODUITPFNL);
    }

    /**
     * Sets <code>value</code> as attribute value for idpartieproduitpfnl using the alias name Idpartieproduitpfnl.
     * @param value value to set the idpartieproduitpfnl
     */
    public void setIdpartieproduitpfnl(BigDecimal value) {
        setAttributeInternal(IDPARTIEPRODUITPFNL, value);
    }

    /**
     * Gets the attribute value for idregions using the alias name Idregions.
     * @return the idregions
     */
    public BigDecimal getIdregions() {
        return (BigDecimal) getAttributeInternal(IDREGIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for idregions using the alias name Idregions.
     * @param value value to set the idregions
     */
    public void setIdregions(BigDecimal value) {
        setAttributeInternal(IDREGIONS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute idunitemesureconsultation.
     * @return the idunitemesureconsultation
     */
    public BigDecimal getidunitemesureconsultation() {
        return (BigDecimal) getAttributeInternal(IDUNITEMESURECONSULTATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute idunitemesureconsultation.
     * @param value value to set the  idunitemesureconsultation
     */
    public void setidunitemesureconsultation(BigDecimal value) {
        setAttributeInternal(IDUNITEMESURECONSULTATION, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DetailpermisView.
     */
    public RowIterator getDetailpermisView() {
        return (RowIterator) getAttributeInternal(DETAILPERMISVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DetailpermisView1.
     */
    public RowIterator getDetailpermisView1() {
        return (RowIterator) getAttributeInternal(DETAILPERMISVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DetailpermisView2.
     */
    public RowIterator getDetailpermisView2() {
        return (RowIterator) getAttributeInternal(DETAILPERMISVIEW2);
    }

    /**
     * Gets the associated <code>PermisViewRowImpl</code> using master-detail link PermisView.
     */
    public PermisViewRowImpl getPermisView() {
        return (PermisViewRowImpl) getAttributeInternal(PERMISVIEW);
    }

    /**
     * Sets the master-detail link PermisView between this object and <code>value</code>.
     */
    public void setPermisView(PermisViewRowImpl value) {
        setAttributeInternal(PERMISVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UnitemesureView1.
     */
    public RowSet getUnitemesureView1() {
        return (RowSet) getAttributeInternal(UNITEMESUREVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PermisView1.
     */
    public RowSet getPermisView1() {
        return (RowSet) getAttributeInternal(PERMISVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartiesproduitspfnlView1.
     */
    public RowSet getPartiesproduitspfnlView1() {
        return (RowSet) getAttributeInternal(PARTIESPRODUITSPFNLVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getLibelleProduitComplet1.
     */
    public RowSet getgetLibelleProduitComplet1() {
        return (RowSet) getAttributeInternal(GETLIBELLEPRODUITCOMPLET1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppModule_RegionView1_1.
     */
    public RowSet getAppModule_RegionView1_1() {
        return (RowSet) getAttributeInternal(APPMODULE_REGIONVIEW1_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppModule_UniteMesureWithPartieProduitPfnl1_1.
     */
    public RowSet getAppModule_UniteMesureWithPartieProduitPfnl1_1() {
        return (RowSet) getAttributeInternal(APPMODULE_UNITEMESUREWITHPARTIEPRODUITPFNL1_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UniteMesureWithPartieProduitPfnl1.
     */
    public RowSet getUniteMesureWithPartieProduitPfnl1() {
        return (RowSet) getAttributeInternal(UNITEMESUREWITHPARTIEPRODUITPFNL1);
    }
}

