package cm.gov.minfof.model.entityviewobject;

import cm.gov.minfof.model.entity.AppModuleImpl;
import cm.gov.minfof.model.entity.ExportpfnlImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 17 20:30:05 WAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExportpfnlViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_EXPORTPFNL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idexportpfnl,
        Idpermis,
        Idpermissionnaire,
        Numeroexport,
        Numeroco,
        Dateexport,
        Idposteexport,
        Idpermis1,
        nomouraisonsociale,
        numeropermis,
        nompostecontrole,
        ExportpfnlView,
        ExportpfnlView1,
        DetailsexportpfnlView,
        PermisView,
        PermissionnairespnflView,
        PermisView1,
        PermissionnairespnflView1,
        PostecontroleView1,
        getPermisExportActif1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDEXPORTPFNL = AttributesEnum.Idexportpfnl.index();
    public static final int IDPERMIS = AttributesEnum.Idpermis.index();
    public static final int IDPERMISSIONNAIRE = AttributesEnum.Idpermissionnaire.index();
    public static final int NUMEROEXPORT = AttributesEnum.Numeroexport.index();
    public static final int NUMEROCO = AttributesEnum.Numeroco.index();
    public static final int DATEEXPORT = AttributesEnum.Dateexport.index();
    public static final int IDPOSTEEXPORT = AttributesEnum.Idposteexport.index();
    public static final int IDPERMIS1 = AttributesEnum.Idpermis1.index();
    public static final int NOMOURAISONSOCIALE = AttributesEnum.nomouraisonsociale.index();
    public static final int NUMEROPERMIS = AttributesEnum.numeropermis.index();
    public static final int NOMPOSTECONTROLE = AttributesEnum.nompostecontrole.index();
    public static final int EXPORTPFNLVIEW = AttributesEnum.ExportpfnlView.index();
    public static final int EXPORTPFNLVIEW1 = AttributesEnum.ExportpfnlView1.index();
    public static final int DETAILSEXPORTPFNLVIEW = AttributesEnum.DetailsexportpfnlView.index();
    public static final int PERMISVIEW = AttributesEnum.PermisView.index();
    public static final int PERMISSIONNAIRESPNFLVIEW = AttributesEnum.PermissionnairespnflView.index();
    public static final int PERMISVIEW1 = AttributesEnum.PermisView1.index();
    public static final int PERMISSIONNAIRESPNFLVIEW1 = AttributesEnum.PermissionnairespnflView1.index();
    public static final int POSTECONTROLEVIEW1 = AttributesEnum.PostecontroleView1.index();
    public static final int GETPERMISEXPORTACTIF1 = AttributesEnum.getPermisExportActif1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ExportpfnlViewRowImpl() {
    }

    /**
     * Gets Exportpfnl entity object.
     * @return the Exportpfnl
     */
    public ExportpfnlImpl getExportpfnl() {
        return (ExportpfnlImpl) getEntity(ENTITY_EXPORTPFNL);
    }

    /**
     * Gets the attribute value for idexportpfnl using the alias name Idexportpfnl.
     * @return the idexportpfnl
     */
    public BigDecimal getIdexportpfnl() {
        return (BigDecimal) getAttributeInternal(IDEXPORTPFNL);
    }

    /**
     * Sets <code>value</code> as attribute value for idexportpfnl using the alias name Idexportpfnl.
     * @param value value to set the idexportpfnl
     */
    public void setIdexportpfnl(BigDecimal value) {
        setAttributeInternal(IDEXPORTPFNL, value);
    }

    /**
     * Gets the attribute value for idpermis using the alias name Idpermis.
     * @return the idpermis
     */
    public BigDecimal getIdpermis() {
        return (BigDecimal) getAttributeInternal(IDPERMIS);
    }

    /**
     * Sets <code>value</code> as attribute value for idpermis using the alias name Idpermis.
     * @param value value to set the idpermis
     */
    public void setIdpermis(BigDecimal value) {
        setAttributeInternal(IDPERMIS, value);
    }

    /**
     * Gets the attribute value for idpermissionnaire using the alias name Idpermissionnaire.
     * @return the idpermissionnaire
     */
    public BigDecimal getIdpermissionnaire() {
        return (BigDecimal) getAttributeInternal(IDPERMISSIONNAIRE);
    }

    /**
     * Sets <code>value</code> as attribute value for idpermissionnaire using the alias name Idpermissionnaire.
     * @param value value to set the idpermissionnaire
     */
    public void setIdpermissionnaire(BigDecimal value) {
        setAttributeInternal(IDPERMISSIONNAIRE, value);
    }

    /**
     * Gets the attribute value for numeroexport using the alias name Numeroexport.
     * @return the numeroexport
     */
    public String getNumeroexport() {
        return (String) getAttributeInternal(NUMEROEXPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for numeroexport using the alias name Numeroexport.
     * @param value value to set the numeroexport
     */
    public void setNumeroexport(String value) {
        setAttributeInternal(NUMEROEXPORT, value);
    }

    /**
     * Gets the attribute value for numeroco using the alias name Numeroco.
     * @return the numeroco
     */
    public String getNumeroco() {
        return (String) getAttributeInternal(NUMEROCO);
    }

    /**
     * Sets <code>value</code> as attribute value for numeroco using the alias name Numeroco.
     * @param value value to set the numeroco
     */
    public void setNumeroco(String value) {
        setAttributeInternal(NUMEROCO, value);
    }

    /**
     * Gets the attribute value for dateexport using the alias name Dateexport.
     * @return the dateexport
     */
    public Timestamp getDateexport() {
        return (Timestamp) getAttributeInternal(DATEEXPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for dateexport using the alias name Dateexport.
     * @param value value to set the dateexport
     */
    public void setDateexport(Timestamp value) {
        setAttributeInternal(DATEEXPORT, value);
    }

    /**
     * Gets the attribute value for idposteexport using the alias name Idposteexport.
     * @return the idposteexport
     */
    public BigDecimal getIdposteexport() {
        return (BigDecimal) getAttributeInternal(IDPOSTEEXPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for idposteexport using the alias name Idposteexport.
     * @param value value to set the idposteexport
     */
    public void setIdposteexport(BigDecimal value) {
        setAttributeInternal(IDPOSTEEXPORT, value);
    }

    /**
     * Gets the attribute value for idpermis using the alias name Idpermis1.
     * @return the idpermis
     */
    public BigDecimal getIdpermis1() {
        return (BigDecimal) getAttributeInternal(IDPERMIS1);
    }

    /**
     * Sets <code>value</code> as attribute value for idpermis using the alias name Idpermis1.
     * @param value value to set the idpermis
     */
    public void setIdpermis1(BigDecimal value) {
        setAttributeInternal(IDPERMIS1, value);
    }

    /**
     * Gets the attribute value for nomouraisonsociale using the alias name nomouraisonsociale.
     * @return the nomouraisonsociale
     */
    public String getnomouraisonsociale() {
        String result = "";
        AppModuleImpl am = (AppModuleImpl)this.getApplicationModule();
        ViewObjectImpl voIm = am.getPermissionnairespnflView1();
        voIm.setWhereClause("Idpermissionnairespnfl="+getIdpermissionnaire());
        voIm.executeQuery();
        if (voIm.hasNext()){
            Row r = voIm.next();
            result = r.getAttribute("Nomouraisonsociale").toString();
            }
        voIm.setWhereClause(null);
        voIm.executeQuery();
        return result;
        //return (String) getAttributeInternal(NOMOURAISONSOCIALE);
    }

    /**
     * Sets <code>value</code> as attribute value for nomouraisonsociale using the alias name nomouraisonsociale.
     * @param value value to set the nomouraisonsociale
     */
    public void setnomouraisonsociale(String value) {
        setAttributeInternal(NOMOURAISONSOCIALE, value);
    }

    /**
     * Gets the attribute value for numeropermis using the alias name numeropermis.
     * @return the numeropermis
     */
    public String getnumeropermis() {
        String result = "";
        AppModuleImpl am = (AppModuleImpl)this.getApplicationModule();
        ViewObjectImpl voIm = am.getPermisView1();
        voIm.setWhereClause("Idpermis="+getIdpermis());
        voIm.executeQuery();
        if (voIm.hasNext()){
            Row r = voIm.next();
            result = r.getAttribute("Numeropermis").toString();
            }
        voIm.setWhereClause(null);
        voIm.executeQuery();
        return result;
      //  return (String) getAttributeInternal(NUMEROPERMIS);
    }

    /**
     * Sets <code>value</code> as attribute value for numeropermis using the alias name numeropermis.
     * @param value value to set the numeropermis
     */
    public void setnumeropermis(String value) {
        setAttributeInternal(NUMEROPERMIS, value);
    }

    /**
     * Gets the attribute value for nompostecontrole using the alias name nompostecontrole.
     * @return the nompostecontrole
     */
    public String getnompostecontrole() {
        String result = "";
        AppModuleImpl am = (AppModuleImpl)this.getApplicationModule();
        ViewObjectImpl voIm = am.getPostecontroleView1();
        voIm.setWhereClause("Idpostecontrole="+getIdposteexport());
        voIm.executeQuery();
        if (voIm.hasNext()){
            Row r = voIm.next();
            result = r.getAttribute("Intituleposte").toString();
            }
        voIm.setWhereClause(null);
        voIm.executeQuery();
        return result;
    //    return (String) getAttributeInternal(NOMPOSTECONTROLE);
    }

    /**
     * Sets <code>value</code> as attribute value for nompostecontrole using the alias name nompostecontrole.
     * @param value value to set the nompostecontrole
     */
    public void setnompostecontrole(String value) {
        setAttributeInternal(NOMPOSTECONTROLE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExportpfnlView.
     */
    public RowIterator getExportpfnlView() {
        return (RowIterator) getAttributeInternal(EXPORTPFNLVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExportpfnlView1.
     */
    public RowIterator getExportpfnlView1() {
        return (RowIterator) getAttributeInternal(EXPORTPFNLVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DetailsexportpfnlView.
     */
    public RowIterator getDetailsexportpfnlView() {
        return (RowIterator) getAttributeInternal(DETAILSEXPORTPFNLVIEW);
    }

    /**
     * Gets the associated <code>ViewRowImpl</code> using master-detail link PermisView.
     */
    public ViewRowImpl getPermisView() {
        return (ViewRowImpl) getAttributeInternal(PERMISVIEW);
    }

    /**
     * Sets the master-detail link PermisView between this object and <code>value</code>.
     */
    public void setPermisView(ViewRowImpl value) {
        setAttributeInternal(PERMISVIEW, value);
    }

    /**
     * Gets the associated <code>ViewRowImpl</code> using master-detail link PermissionnairespnflView.
     */
    public ViewRowImpl getPermissionnairespnflView() {
        return (ViewRowImpl) getAttributeInternal(PERMISSIONNAIRESPNFLVIEW);
    }

    /**
     * Sets the master-detail link PermissionnairespnflView between this object and <code>value</code>.
     */
    public void setPermissionnairespnflView(ViewRowImpl value) {
        setAttributeInternal(PERMISSIONNAIRESPNFLVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PermisView1.
     */
    public RowSet getPermisView1() {
        return (RowSet) getAttributeInternal(PERMISVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PermissionnairespnflView1.
     */
    public RowSet getPermissionnairespnflView1() {
        return (RowSet) getAttributeInternal(PERMISSIONNAIRESPNFLVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PostecontroleView1.
     */
    public RowSet getPostecontroleView1() {
        return (RowSet) getAttributeInternal(POSTECONTROLEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getPermisExportActif1.
     */
    public RowSet getgetPermisExportActif1() {
        return (RowSet) getAttributeInternal(GETPERMISEXPORTACTIF1);
    }
}

