package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 17 09:57:22 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getLastIdCategorieUniteMesureImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getLastIdCategorieUniteMesureImpl() {
    }
}

