package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 04 23:27:43 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getLibelleProduitCompletDefImpl extends ViewDefImpl {
    public getLibelleProduitCompletDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public getLibelleProduitCompletDefImpl() {
    }
}

