package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 02 04:01:19 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getLibelleFixeImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getLibelleFixeImpl() {
    }
}

