package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 12 15:28:59 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getLastIdPermissionnairePfnlImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getLastIdPermissionnairePfnlImpl() {
    }
}

