package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 06 09:05:54 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getLastIdPartiesRecolteesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getLastIdPartiesRecolteesImpl() {
    }
}

