package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 05 22:28:38 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getLastIdDepartementsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public getLastIdDepartementsImpl() {
    }
}

