package cm.gov.minfof.model.entityviewobject;

import cm.gov.minfof.model.entityviewobject.common.Longtext1;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 16 15:50:26 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class getRegionUserRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Idregions,
        Nomregion,
        Coderegion,
        Descriptionregions,
        Cheflieuregion,
        Abreviationregion;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDREGIONS = AttributesEnum.Idregions.index();
    public static final int NOMREGION = AttributesEnum.Nomregion.index();
    public static final int CODEREGION = AttributesEnum.Coderegion.index();
    public static final int DESCRIPTIONREGIONS = AttributesEnum.Descriptionregions.index();
    public static final int CHEFLIEUREGION = AttributesEnum.Cheflieuregion.index();
    public static final int ABREVIATIONREGION = AttributesEnum.Abreviationregion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public getRegionUserRowImpl() {
    }
}

