package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 15 16:21:19 WAT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LettreVoitureMulticritereDepartImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LettreVoitureMulticritereDepartImpl() {
    }
}

