package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 22 12:34:48 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class localiteCompletImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public localiteCompletImpl() {
    }
}

