package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 15 05:41:02 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocaliteLettreVoitureDefImpl extends ViewDefImpl {
    public LocaliteLettreVoitureDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public LocaliteLettreVoitureDefImpl() {
    }
}

