package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 20 04:03:17 WAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PermissionnaireEtPermisImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PermissionnaireEtPermisImpl() {
    }
}

