package cm.gov.minfof.model.entityviewobject;

import cm.gov.minfof.model.entity.AppModuleImpl;
import cm.gov.minfof.model.entity.CommuneImpl;
import cm.gov.minfof.model.entity.PermissionnairespnflImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 26 15:51:03 CET 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PermissionnairespnflViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_PERMISSIONNAIRESPNFL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Nomouraisonsociale,
        Statut,
        Siegesocial,
        Nbreemploye,
        Contact,
        Mail,
        Codepnfl,
        Natureactivite,
        Numceqe,
        Idpermissionnairespnfl,
        Nui,
        Profession,
        Typepersonne,
        Adressep,
        Sexe,
        Idcommune,
        nomcommune,
        idregional,
        iddepartemental,
        DetailscollectepfnlView,
        PermisView,
        ExportpfnlView,
        listeStatutPermissionnaire1,
        listeTypePersonne1,
        listeSexe1,
        listeExploitant1,
        CommuneView1,
        getComunneUser1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NOMOURAISONSOCIALE = AttributesEnum.Nomouraisonsociale.index();
    public static final int STATUT = AttributesEnum.Statut.index();
    public static final int SIEGESOCIAL = AttributesEnum.Siegesocial.index();
    public static final int NBREEMPLOYE = AttributesEnum.Nbreemploye.index();
    public static final int CONTACT = AttributesEnum.Contact.index();
    public static final int MAIL = AttributesEnum.Mail.index();
    public static final int CODEPNFL = AttributesEnum.Codepnfl.index();
    public static final int NATUREACTIVITE = AttributesEnum.Natureactivite.index();
    public static final int NUMCEQE = AttributesEnum.Numceqe.index();
    public static final int IDPERMISSIONNAIRESPNFL = AttributesEnum.Idpermissionnairespnfl.index();
    public static final int NUI = AttributesEnum.Nui.index();
    public static final int PROFESSION = AttributesEnum.Profession.index();
    public static final int TYPEPERSONNE = AttributesEnum.Typepersonne.index();
    public static final int ADRESSEP = AttributesEnum.Adressep.index();
    public static final int SEXE = AttributesEnum.Sexe.index();
    public static final int IDCOMMUNE = AttributesEnum.Idcommune.index();
    public static final int NOMCOMMUNE = AttributesEnum.nomcommune.index();
    public static final int IDREGIONAL = AttributesEnum.idregional.index();
    public static final int IDDEPARTEMENTAL = AttributesEnum.iddepartemental.index();
    public static final int DETAILSCOLLECTEPFNLVIEW = AttributesEnum.DetailscollectepfnlView.index();
    public static final int PERMISVIEW = AttributesEnum.PermisView.index();
    public static final int EXPORTPFNLVIEW = AttributesEnum.ExportpfnlView.index();
    public static final int LISTESTATUTPERMISSIONNAIRE1 = AttributesEnum.listeStatutPermissionnaire1.index();
    public static final int LISTETYPEPERSONNE1 = AttributesEnum.listeTypePersonne1.index();
    public static final int LISTESEXE1 = AttributesEnum.listeSexe1.index();
    public static final int LISTEEXPLOITANT1 = AttributesEnum.listeExploitant1.index();
    public static final int COMMUNEVIEW1 = AttributesEnum.CommuneView1.index();
    public static final int GETCOMUNNEUSER1 = AttributesEnum.getComunneUser1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PermissionnairespnflViewRowImpl() {
    }


}

