package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 22 12:17:51 WAT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PosteControleCompletRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Codeposte,
        Intituleposte,
        Codecommune,
        Nomcommune,
        Codedepartement,
        Nomdepartement,
        Nomcheflieu,
        Coderegion,
        Nomregion,
        Cheflieuregion;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CODEPOSTE = AttributesEnum.Codeposte.index();
    public static final int INTITULEPOSTE = AttributesEnum.Intituleposte.index();
    public static final int CODECOMMUNE = AttributesEnum.Codecommune.index();
    public static final int NOMCOMMUNE = AttributesEnum.Nomcommune.index();
    public static final int CODEDEPARTEMENT = AttributesEnum.Codedepartement.index();
    public static final int NOMDEPARTEMENT = AttributesEnum.Nomdepartement.index();
    public static final int NOMCHEFLIEU = AttributesEnum.Nomcheflieu.index();
    public static final int CODEREGION = AttributesEnum.Coderegion.index();
    public static final int NOMREGION = AttributesEnum.Nomregion.index();
    public static final int CHEFLIEUREGION = AttributesEnum.Cheflieuregion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PosteControleCompletRowImpl() {
    }
}

