package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 09 07:23:00 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class typeDocumentViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        idtypedoc,
        libelleTypeDocument,
        PermisView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDTYPEDOC = AttributesEnum.idtypedoc.index();
    public static final int LIBELLETYPEDOCUMENT = AttributesEnum.libelleTypeDocument.index();
    public static final int PERMISVIEW1 = AttributesEnum.PermisView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public typeDocumentViewRowImpl() {
    }
}

