package cm.gov.minfof.model.entityviewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 29 12:51:36 WAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class typeDocViewFinalImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public typeDocViewFinalImpl() {
    }
}

