package cm.gov.minfof.model.entityviewobject;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 21 15:00:02 WAT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UnitemesureViewImpl extends VueImplementation {
    /**
     * This is the default constructor (do not remove).
     */
    public UnitemesureViewImpl() {
    }

    /**
     * Returns the variable value for idcategoriebind.
     * @return variable value for idcategoriebind
     */
    public BigDecimal getidcategoriebind() {
        return (BigDecimal) ensureVariableManager().getVariableValue("idcategoriebind");
    }

    /**
     * Sets <code>value</code> for variable idcategoriebind.
     * @param value value to bind as idcategoriebind
     */
    public void setidcategoriebind(BigDecimal value) {
        ensureVariableManager().setVariableValue("idcategoriebind", value);
    }
}

