package cm.gov.minfof.model.entityviewobject;

import cm.gov.minfof.model.entity.UtilisateurImpl;


import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 10 12:39:28 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UtilisateurViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_UTILISATEUR = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Loginuser,
        Passworduser,
        Nomuser,
        Telephone,
        Niveauintervention,
        Idregions,
        Iddepartements,
        Idgroupe,
        Saisiecollecte,
        Saisieexport,
        Saisietransit,
        Idutilisateur,
        Emailuser,
        Premiereconnexion,
        UtilisateurView,
        UtilisateurView1,
        UtilisateurView2,
        RegionView1,
        DepartementView1,
        GroupeutilisateurView1,
        NiveauValidationView1,
        getDepartementUser1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LOGINUSER = AttributesEnum.Loginuser.index();
    public static final int PASSWORDUSER = AttributesEnum.Passworduser.index();
    public static final int NOMUSER = AttributesEnum.Nomuser.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();
    public static final int NIVEAUINTERVENTION = AttributesEnum.Niveauintervention.index();
    public static final int IDREGIONS = AttributesEnum.Idregions.index();
    public static final int IDDEPARTEMENTS = AttributesEnum.Iddepartements.index();
    public static final int IDGROUPE = AttributesEnum.Idgroupe.index();
    public static final int SAISIECOLLECTE = AttributesEnum.Saisiecollecte.index();
    public static final int SAISIEEXPORT = AttributesEnum.Saisieexport.index();
    public static final int SAISIETRANSIT = AttributesEnum.Saisietransit.index();
    public static final int IDUTILISATEUR = AttributesEnum.Idutilisateur.index();
    public static final int EMAILUSER = AttributesEnum.Emailuser.index();
    public static final int PREMIERECONNEXION = AttributesEnum.Premiereconnexion.index();
    public static final int UTILISATEURVIEW = AttributesEnum.UtilisateurView.index();
    public static final int UTILISATEURVIEW1 = AttributesEnum.UtilisateurView1.index();
    public static final int UTILISATEURVIEW2 = AttributesEnum.UtilisateurView2.index();
    public static final int REGIONVIEW1 = AttributesEnum.RegionView1.index();
    public static final int DEPARTEMENTVIEW1 = AttributesEnum.DepartementView1.index();
    public static final int GROUPEUTILISATEURVIEW1 = AttributesEnum.GroupeutilisateurView1.index();
    public static final int NIVEAUVALIDATIONVIEW1 = AttributesEnum.NiveauValidationView1.index();
    public static final int GETDEPARTEMENTUSER1 = AttributesEnum.getDepartementUser1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UtilisateurViewRowImpl() {
    }

    /**
     * Gets Utilisateur entity object.
     * @return the Utilisateur
     */
    public UtilisateurImpl getUtilisateur() {
        return (UtilisateurImpl) getEntity(ENTITY_UTILISATEUR);
    }

    /**
     * Gets the attribute value for loginuser using the alias name Loginuser.
     * @return the loginuser
     */
    public String getLoginuser() {
        return (String) getAttributeInternal(LOGINUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for loginuser using the alias name Loginuser.
     * @param value value to set the loginuser
     */
    public void setLoginuser(String value) {
        setAttributeInternal(LOGINUSER, value);
    }

    /**
     * Gets the attribute value for passworduser using the alias name Passworduser.
     * @return the passworduser
     */
    public String getPassworduser() {
        return (String) getAttributeInternal(PASSWORDUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for passworduser using the alias name Passworduser.
     * @param value value to set the passworduser
     */
    public void setPassworduser(String value) {
        setAttributeInternal(PASSWORDUSER, value);
    }

    /**
     * Gets the attribute value for nomuser using the alias name Nomuser.
     * @return the nomuser
     */
    public String getNomuser() {
        return (String) getAttributeInternal(NOMUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for nomuser using the alias name Nomuser.
     * @param value value to set the nomuser
     */
    public void setNomuser(String value) {
        setAttributeInternal(NOMUSER, value);
    }

    /**
     * Gets the attribute value for telephone using the alias name Telephone.
     * @return the telephone
     */
    public String getTelephone() {
        return (String) getAttributeInternal(TELEPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for telephone using the alias name Telephone.
     * @param value value to set the telephone
     */
    public void setTelephone(String value) {
        setAttributeInternal(TELEPHONE, value);
    }

    /**
     * Gets the attribute value for niveauintervention using the alias name Niveauintervention.
     * @return the niveauintervention
     */
    public Integer getNiveauintervention() {
        return (Integer) getAttributeInternal(NIVEAUINTERVENTION);
    }

    /**
     * Sets <code>value</code> as attribute value for niveauintervention using the alias name Niveauintervention.
     * @param value value to set the niveauintervention
     */
    public void setNiveauintervention(Integer value) {
        setAttributeInternal(NIVEAUINTERVENTION, value);
    }

    /**
     * Gets the attribute value for idregions using the alias name Idregions.
     * @return the idregions
     */
    public BigDecimal getIdregions() {
        return (BigDecimal) getAttributeInternal(IDREGIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for idregions using the alias name Idregions.
     * @param value value to set the idregions
     */
    public void setIdregions(BigDecimal value) {
        setAttributeInternal(IDREGIONS, value);
    }

    /**
     * Gets the attribute value for iddepartements using the alias name Iddepartements.
     * @return the iddepartements
     */
    public BigDecimal getIddepartements() {
        return (BigDecimal) getAttributeInternal(IDDEPARTEMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for iddepartements using the alias name Iddepartements.
     * @param value value to set the iddepartements
     */
    public void setIddepartements(BigDecimal value) {
        setAttributeInternal(IDDEPARTEMENTS, value);
    }

    /**
     * Gets the attribute value for idgroupe using the alias name Idgroupe.
     * @return the idgroupe
     */
    public BigDecimal getIdgroupe() {
        return (BigDecimal) getAttributeInternal(IDGROUPE);
    }

    /**
     * Sets <code>value</code> as attribute value for idgroupe using the alias name Idgroupe.
     * @param value value to set the idgroupe
     */
    public void setIdgroupe(BigDecimal value) {
        setAttributeInternal(IDGROUPE, value);
    }

    /**
     * Gets the attribute value for saisiecollecte using the alias name Saisiecollecte.
     * @return the saisiecollecte
     */
    public Boolean getSaisiecollecte() {
        return (Boolean) getAttributeInternal(SAISIECOLLECTE);
    }

    /**
     * Sets <code>value</code> as attribute value for saisiecollecte using the alias name Saisiecollecte.
     * @param value value to set the saisiecollecte
     */
    public void setSaisiecollecte(Boolean value) {
        setAttributeInternal(SAISIECOLLECTE, value);
    }

    /**
     * Gets the attribute value for saisieexport using the alias name Saisieexport.
     * @return the saisieexport
     */
    public Boolean getSaisieexport() {
        return (Boolean) getAttributeInternal(SAISIEEXPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for saisieexport using the alias name Saisieexport.
     * @param value value to set the saisieexport
     */
    public void setSaisieexport(Boolean value) {
        setAttributeInternal(SAISIEEXPORT, value);
    }

    /**
     * Gets the attribute value for saisietransit using the alias name Saisietransit.
     * @return the saisietransit
     */
    public Boolean getSaisietransit() {
        return (Boolean) getAttributeInternal(SAISIETRANSIT);
    }

    /**
     * Sets <code>value</code> as attribute value for saisietransit using the alias name Saisietransit.
     * @param value value to set the saisietransit
     */
    public void setSaisietransit(Boolean value) {
        setAttributeInternal(SAISIETRANSIT, value);
    }

    /**
     * Gets the attribute value for idutilisateur using the alias name Idutilisateur.
     * @return the idutilisateur
     */
    public BigDecimal getIdutilisateur() {
        return (BigDecimal) getAttributeInternal(IDUTILISATEUR);
    }

    /**
     * Sets <code>value</code> as attribute value for idutilisateur using the alias name Idutilisateur.
     * @param value value to set the idutilisateur
     */
    public void setIdutilisateur(BigDecimal value) {
        setAttributeInternal(IDUTILISATEUR, value);
    }

    /**
     * Gets the attribute value for emailuser using the alias name Emailuser.
     * @return the emailuser
     */
    public String getEmailuser() {
        return (String) getAttributeInternal(EMAILUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for emailuser using the alias name Emailuser.
     * @param value value to set the emailuser
     */
    public void setEmailuser(String value) {
        setAttributeInternal(EMAILUSER, value);
    }

    /**
     * Gets the attribute value for premiereconnexion using the alias name Premiereconnexion.
     * @return the premiereconnexion
     */
    public Boolean getPremiereconnexion() {
        return (Boolean) getAttributeInternal(PREMIERECONNEXION);
    }

    /**
     * Sets <code>value</code> as attribute value for premiereconnexion using the alias name Premiereconnexion.
     * @param value value to set the premiereconnexion
     */
    public void setPremiereconnexion(Boolean value) {
        setAttributeInternal(PREMIERECONNEXION, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateurView.
     */
    public RowIterator getUtilisateurView() {
        return (RowIterator) getAttributeInternal(UTILISATEURVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateurView1.
     */
    public RowIterator getUtilisateurView1() {
        return (RowIterator) getAttributeInternal(UTILISATEURVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UtilisateurView2.
     */
    public RowIterator getUtilisateurView2() {
        return (RowIterator) getAttributeInternal(UTILISATEURVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionView1.
     */
    public RowSet getRegionView1() {
        return (RowSet) getAttributeInternal(REGIONVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartementView1.
     */
    public RowSet getDepartementView1() {
        return (RowSet) getAttributeInternal(DEPARTEMENTVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupeutilisateurView1.
     */
    public RowSet getGroupeutilisateurView1() {
        return (RowSet) getAttributeInternal(GROUPEUTILISATEURVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NiveauValidationView1.
     */
    public RowSet getNiveauValidationView1() {
        return (RowSet) getAttributeInternal(NIVEAUVALIDATIONVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> getDepartementUser1.
     */
    public RowSet getgetDepartementUser1() {
        return (RowSet) getAttributeInternal(GETDEPARTEMENTUSER1);
    }
}

